# Generated by Django 5.0.4 on 2024-05-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address1',
            new_name='shipping_address3',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address2',
            new_name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_zipcode',
        ),
    ]
